- name: Ensuring group vars
  hosts: "hosts"
  gather_facts: no
  connection: local
  user: root
  tasks:
    - name: Ensuring existing group vars are well applied
      assert:
        that:
          - "openstack_release is defined"
    - name: Ensuring babar is well defined
      assert:
        that:
          - "babar == 'elephant'"
    - name: Ensuring lxc_hosts_package_state is well overridden
      assert:
        that:
          - "lxc_hosts_package_state == 'present'"

- name: Ensuring host vars
  hosts: localhost
  gather_facts: no
  connection: local
  user: root
  tasks:
    - name: Ensuring tintin has milou
      assert:
        that:
          - "tintin == 'milou'"
    - name: Ensuring security_package_state is overridden
      assert:
        that:
          - "security_package_state == 'present'"
